"""Cypher generation from the curated seed + the shared biomarker catalog.

``seed.cypher`` is a generated, committed artifact (``python -m graph_service.cypher``);
a test fails if it is stale. Parameterised statements for model-derived data
(functional bands, correlations) are produced here too so the loader and the
connector share one definition.
"""

from __future__ import annotations

import json
from pathlib import Path

from polymarker_common.catalog import load_catalog

from graph_service import seed_data as seed
from graph_service.connector import is_verified

ROOT = Path(__file__).resolve().parents[1]
SEED_PATH = ROOT / "seed.cypher"
SCHEMA_PATH = ROOT / "schema.cypher"


def _lit(value) -> str:
    """Cypher literal for str / number / bool / None (json quoting is valid Cypher)."""
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return repr(float(value))
    return json.dumps(str(value), ensure_ascii=False)


def _props(d: dict) -> str:
    return "{" + ", ".join(f"{k}: {_lit(v)}" for k, v in d.items()) + "}"


def _edge_props(edge: dict) -> dict:
    level = edge["evidence_level"]
    props = {
        "source": edge["source"],
        "evidence_level": level,
        "verified": is_verified(level),
        "note": edge.get("note", ""),
    }
    requires = edge.get("requires")
    if requires:
        props["requires_biomarker"] = requires.get("biomarker")
        props["requires_within_reference"] = bool(requires.get("within_reference"))
        props["requires_above"] = requires.get("above")
    return props


def generate_seed() -> str:
    out: list[str] = [
        "// GENERATED by `python -m graph_service.cypher` from graph_service/seed_data.py",
        "// and polymarker_common/data/biomarkers.json. Do not edit by hand.",
        "// Every relationship carries source + evidence_level; verified=false marks unverified edges.",
        "",
        "// Sources",
    ]
    for sid, s in seed.SOURCES.items():
        out.append(f"MERGE (s:Source {{id: {_lit(sid)}}}) SET s += {_props(s)};")

    out += ["", "// Biomarkers, LOINC codes, reference intervals"]
    for key, m in load_catalog().items():
        out.append(
            f"MERGE (b:Biomarker {{key: {_lit(key)}}}) SET b += "
            f"{_props({'name': m.display, 'long_name': m.long_name, 'panel': m.panel, 'canonical_unit': m.canonical_unit})};"
        )
        out.append(f"MERGE (l:LOINC {{code: {_lit(m.loinc)}}}) SET l.name = {_lit(m.loinc_name)};")
        out.append(
            f"MATCH (b:Biomarker {{key: {_lit(key)}}}), (l:LOINC {{code: {_lit(m.loinc)}}}) "
            f"MERGE (b)-[r:CODED_AS]->(l) SET r += {_props({'source': 'loinc', 'evidence_level': 'guideline', 'verified': True})};"
        )
        ranges = [("reference", None, m.reference)] + [
            (f"reference_{sex.lower()}", sex, r) for sex, r in m.reference_by_sex.items()
        ]
        for suffix, sex, rng in ranges:
            rid = f"{key.lower()}_{suffix}"
            props = {
                "biomarker": key,
                "kind": "reference",
                "sex": sex,
                "low": rng.low,
                "high": rng.high,
                "unit": m.canonical_unit,
                "label": f"{m.display} laboratory reference interval"
                + (f" ({sex})" if sex else ""),
                "source": "catalog",
                "evidence_level": "expert_consensus",
                "verified": True,
            }
            out.append(f"MERGE (r:FunctionalRange {{id: {_lit(rid)}}}) SET r += {_props(props)};")
            out.append(
                f"MATCH (b:Biomarker {{key: {_lit(key)}}}), (r:FunctionalRange {{id: {_lit(rid)}}}) MERGE (b)-[:HAS_RANGE]->(r);"
            )

    out += ["", "// Conditions and symptoms"]
    for cid, name in seed.CONDITIONS.items():
        out.append(f"MERGE (c:Condition {{id: {_lit(cid)}}}) SET c.name = {_lit(name)};")
    for sid, name in seed.SYMPTOMS.items():
        out.append(f"MERGE (s:Symptom {{id: {_lit(sid)}}}) SET s.name = {_lit(name)};")

    out += ["", "// Literature thresholds"]
    catalog = load_catalog()
    for t in seed.THRESHOLDS:
        props = {
            "biomarker": t["biomarker"],
            "kind": "threshold",
            "op": t["op"],
            "value": t["value"],
            "unit": catalog[t["biomarker"]].canonical_unit,
            "label": t["label"],
        }
        out.append(f"MERGE (r:FunctionalRange {{id: {_lit(t['id'])}}}) SET r += {_props(props)};")
        out.append(
            f"MATCH (b:Biomarker {{key: {_lit(t['biomarker'])}}}), (r:FunctionalRange {{id: {_lit(t['id'])}}}) "
            "MERGE (b)-[:HAS_RANGE]->(r);"
        )

    out += ["", "// Threshold -> condition evidence"]
    for e in seed.THRESHOLD_EDGES:
        out.append(
            f"MATCH (r:FunctionalRange {{id: {_lit(e['from'])}}}), (c:Condition {{id: {_lit(e['to'])}}}) "
            f"MERGE (r)-[x:{e['type']}]->(c) SET x += {_props(_edge_props(e))};"
        )

    out += ["", "// Condition -> symptom evidence"]
    for e in seed.PRESENTS_WITH:
        out.append(
            f"MATCH (c:Condition {{id: {_lit(e['from'])}}}), (s:Symptom {{id: {_lit(e['to'])}}}) "
            f"MERGE (c)-[x:PRESENTS_WITH]->(s) SET x += {_props(_edge_props(e))};"
        )

    out += ["", "// Curated biomarker correlations"]
    for e in seed.BIOMARKER_CORRELATIONS:
        props = _edge_props(e) | {"direction": e["direction"]}
        out.append(
            f"MATCH (a:Biomarker {{key: {_lit(e['from'])}}}), (b:Biomarker {{key: {_lit(e['to'])}}}) "
            f"MERGE (a)-[x:CORRELATES_WITH]->(b) SET x += {_props(props)};"
        )
    return "\n".join(out) + "\n"


def functional_band_statements(bands: dict[str, dict]):
    """bands: {marker_key: {low, high, unit?, target?, method?}} from bda_engine artifacts."""
    catalog = load_catalog()
    for key, band in bands.items():
        if key not in catalog:
            continue
        rid = f"{key.lower()}_functional_band"
        props = {
            "biomarker": key,
            "kind": "functional_band",
            "low": float(band["low"]),
            "high": float(band["high"]),
            "unit": catalog[key].canonical_unit,
            "label": f"{catalog[key].display} functional band (synthetic-derived)",
            "method": band.get("method", "bda_engine"),
            "source": "bda_engine",
            "evidence_level": "synthetic_derived",
            "verified": False,
        }
        yield (
            "MERGE (r:FunctionalRange {id: $id}) SET r += $props "
            "WITH r MATCH (b:Biomarker {key: $key}) MERGE (b)-[:HAS_RANGE]->(r)",
            {"id": rid, "props": props, "key": key},
        )


def correlation_statements(correlations: list[dict]):
    """correlations: [{from: marker, to: symptom_id|marker, rho, direction}] (synthetic-derived)."""
    for c in correlations:
        props = {
            "rho": float(c.get("rho", 0.0)),
            "direction": c.get("direction", "positive" if c.get("rho", 0) >= 0 else "inverse"),
            "source": "bda_engine",
            "evidence_level": "synthetic_derived",
            "verified": False,
        }
        label = "Symptom" if c["to"] in seed.SYMPTOMS else "Biomarker"
        prop = "id" if label == "Symptom" else "key"
        yield (
            f"MATCH (a:Biomarker {{key: $from}}), (b:{label} {{{prop}: $to}}) "
            "MERGE (a)-[x:CORRELATES_WITH]->(b) SET x += $props",
            {"from": c["from"], "to": c["to"], "props": props},
        )


def split_statements(text: str) -> list[str]:
    body = "\n".join(line for line in text.splitlines() if not line.strip().startswith("//"))
    return [s.strip() for s in body.split(";") if s.strip()]


if __name__ == "__main__":
    SEED_PATH.write_text(generate_seed(), encoding="utf-8")
    print(f"wrote {SEED_PATH}")
