-- PolyMarker backend schema (PostgreSQL 14+; Supabase or plain Postgres).
-- Idempotent: applied by `npm run migrate` and on server start (DB_AUTO_MIGRATE).
--
-- Ids are 24-hex strings generated by the backend. The ai-service validates
-- patient/report ids with that format before using them in paths, and its
-- guardrails redact them from patient-facing text.
--
-- Row level security is enabled on every table with no policies: Supabase's
-- public Data API (anon/authenticated keys) can read nothing. The backend
-- connects as the table owner, which bypasses RLS.

CREATE TABLE IF NOT EXISTS users (
    id           char(24) PRIMARY KEY,
    name         text NOT NULL,
    email        text NOT NULL UNIQUE CHECK (email = lower(email)),
    password     text NOT NULL,
    role         text NOT NULL DEFAULT 'patient' CHECK (role IN ('patient', 'clinician')),
    sex          text CHECK (sex IN ('F', 'M')),
    birth_year   integer CHECK (birth_year BETWEEN 1900 AND 2100),
    created_at   timestamptz NOT NULL DEFAULT now(),
    updated_at   timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS users_role_idx ON users (role);

CREATE TABLE IF NOT EXISTS admins (
    id           char(24) PRIMARY KEY,
    name         text NOT NULL,
    email        text NOT NULL UNIQUE CHECK (email = lower(email)),
    password     text NOT NULL,
    created_at   timestamptz NOT NULL DEFAULT now(),
    updated_at   timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS symptom_entries (
    id                  char(24) PRIMARY KEY,
    patient_id          char(24) NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    fatigue_severity    smallint NOT NULL CHECK (fatigue_severity BETWEEN 1 AND 10),
    brain_fog_frequency text NOT NULL CHECK (brain_fog_frequency IN ('never', 'rarely', 'sometimes', 'often', 'always')),
    hair_loss           text NOT NULL CHECK (hair_loss IN ('none', 'mild', 'moderate', 'severe')),
    notes               text NOT NULL DEFAULT '',
    created_at          timestamptz NOT NULL DEFAULT now(),
    updated_at          timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS symptom_entries_patient_idx ON symptom_entries (patient_id, created_at DESC);

CREATE TABLE IF NOT EXISTS reports (
    id                   char(24) PRIMARY KEY,
    patient_id           char(24) NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    original_name        text NOT NULL,
    storage_path         text NOT NULL,
    mime_type            text NOT NULL,
    size                 integer NOT NULL,
    status               text NOT NULL DEFAULT 'processing'
                         CHECK (status IN ('processing', 'pending_clinician_review', 'approved', 'rejected', 'failed')),
    job_id               text,
    job_error            text,
    -- PROMs snapshot sent with the upload (from the latest symptom intake).
    proms                jsonb,
    -- Unified interpretation JSON from the ai-service. Never shown to the
    -- patient before a clinician approves it.
    interpretation       jsonb,
    escalation_level     text NOT NULL DEFAULT 'routine'
                         CHECK (escalation_level IN ('routine', 'priority', 'urgent', 'emergency')),
    review               jsonb,
    audit_trail          jsonb NOT NULL DEFAULT '[]'::jsonb,
    synthetic_data_label text NOT NULL,
    created_at           timestamptz NOT NULL DEFAULT now(),
    updated_at           timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS reports_patient_idx ON reports (patient_id, created_at DESC);
CREATE INDEX IF NOT EXISTS reports_status_idx ON reports (status, created_at);

CREATE TABLE IF NOT EXISTS documents (
    id            char(24) PRIMARY KEY,
    user_id       char(24) NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    original_name text NOT NULL,
    mime_type     text NOT NULL,
    size          integer NOT NULL,
    storage_path  text NOT NULL,
    job_id        text,
    status        text NOT NULL DEFAULT 'uploaded' CHECK (status IN ('uploaded', 'processing', 'ready', 'failed')),
    created_at    timestamptz NOT NULL DEFAULT now(),
    updated_at    timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS documents_user_idx ON documents (user_id);

CREATE TABLE IF NOT EXISTS conversations (
    id          char(24) PRIMARY KEY,
    user_id     char(24) NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    title       text NOT NULL DEFAULT 'New Conversation',
    thread_id   text NOT NULL UNIQUE,
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS conversations_user_idx ON conversations (user_id, updated_at DESC);

CREATE TABLE IF NOT EXISTS messages (
    id              char(24) PRIMARY KEY,
    conversation_id char(24) NOT NULL REFERENCES conversations (id) ON DELETE CASCADE,
    role            text NOT NULL CHECK (role IN ('user', 'assistant')),
    content         text NOT NULL,
    -- Deterministic escalation computed by the ai-service guardrails.
    escalation      jsonb,
    created_at      timestamptz NOT NULL DEFAULT clock_timestamp(),
    updated_at      timestamptz NOT NULL DEFAULT clock_timestamp()
);
CREATE INDEX IF NOT EXISTS messages_conversation_idx ON messages (conversation_id, created_at);

ALTER TABLE users           ENABLE ROW LEVEL SECURITY;
ALTER TABLE admins          ENABLE ROW LEVEL SECURITY;
ALTER TABLE symptom_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE reports         ENABLE ROW LEVEL SECURITY;
ALTER TABLE documents       ENABLE ROW LEVEL SECURITY;
ALTER TABLE conversations   ENABLE ROW LEVEL SECURITY;
ALTER TABLE messages        ENABLE ROW LEVEL SECURITY;
