// GENERATED by `python -m graph_service.cypher` from graph_service/seed_data.py
// and polymarker_common/data/biomarkers.json. Do not edit by hand.
// Every relationship carries source + evidence_level; verified=false marks unverified edges.

// Sources
MERGE (s:Source {id: "who_ferritin_2020"}) SET s += {title: "WHO guideline on use of ferritin concentrations to assess iron status in individuals and populations", publisher: "World Health Organization", year: "2020"};
MERGE (s:Source {id: "nih_ods_vitd"}) SET s += {title: "Vitamin D - Fact Sheet for Health Professionals", publisher: "NIH Office of Dietary Supplements", year: "2024"};
MERGE (s:Source {id: "nih_ods_b12"}) SET s += {title: "Vitamin B12 - Fact Sheet for Health Professionals", publisher: "NIH Office of Dietary Supplements", year: "2024"};
MERGE (s:Source {id: "nih_ods_mg"}) SET s += {title: "Magnesium - Fact Sheet for Health Professionals", publisher: "NIH Office of Dietary Supplements", year: "2022"};
MERGE (s:Source {id: "nih_ods_zinc"}) SET s += {title: "Zinc - Fact Sheet for Health Professionals", publisher: "NIH Office of Dietary Supplements", year: "2022"};
MERGE (s:Source {id: "ata_aace_2012"}) SET s += {title: "Clinical Practice Guidelines for Hypothyroidism in Adults (Garber et al., Thyroid 2012)", publisher: "American Thyroid Association / AACE", year: "2012"};
MERGE (s:Source {id: "ata_patient"}) SET s += {title: "Hypothyroidism patient information", publisher: "American Thyroid Association", year: "2024"};
MERGE (s:Source {id: "curated_hypothesis"}) SET s += {title: "Curated hypothesis pending literature review", publisher: "PolyMarker Analytics project team", year: "2026"};
MERGE (s:Source {id: "bda_engine"}) SET s += {title: "PolyMarker bda_engine discovery run on synthetic cohort", publisher: "PolyMarker Analytics (synthetic data)", year: "2026"};

// Biomarkers, LOINC codes, reference intervals
MERGE (b:Biomarker {key: "TSH"}) SET b += {name: "TSH", long_name: "Thyroid-stimulating hormone", panel: "thyroid", canonical_unit: "mIU/L"};
MERGE (l:LOINC {code: "3016-3"}) SET l.name = "Thyrotropin [Units/volume] in Serum or Plasma";
MATCH (b:Biomarker {key: "TSH"}) MATCH (l:LOINC {code: "3016-3"}) MERGE (b)-[r:CODED_AS]->(l) SET r += {source: "loinc", evidence_level: "guideline", verified: true};
MERGE (r:FunctionalRange {id: "tsh_reference"}) SET r += {biomarker: "TSH", kind: "reference", sex: null, low: 0.4, high: 4.0, unit: "mIU/L", label: "TSH laboratory reference interval", source: "catalog", evidence_level: "expert_consensus", verified: true};
MATCH (b:Biomarker {key: "TSH"}) MATCH (r:FunctionalRange {id: "tsh_reference"}) MERGE (b)-[:HAS_RANGE]->(r);
MERGE (b:Biomarker {key: "FT3"}) SET b += {name: "Free T3", long_name: "Free triiodothyronine", panel: "thyroid", canonical_unit: "pmol/L"};
MERGE (l:LOINC {code: "3051-0"}) SET l.name = "Triiodothyronine (T3) Free [Mass/volume] in Serum or Plasma";
MATCH (b:Biomarker {key: "FT3"}) MATCH (l:LOINC {code: "3051-0"}) MERGE (b)-[r:CODED_AS]->(l) SET r += {source: "loinc", evidence_level: "guideline", verified: true};
MERGE (r:FunctionalRange {id: "ft3_reference"}) SET r += {biomarker: "FT3", kind: "reference", sex: null, low: 3.1, high: 6.8, unit: "pmol/L", label: "Free T3 laboratory reference interval", source: "catalog", evidence_level: "expert_consensus", verified: true};
MATCH (b:Biomarker {key: "FT3"}) MATCH (r:FunctionalRange {id: "ft3_reference"}) MERGE (b)-[:HAS_RANGE]->(r);
MERGE (b:Biomarker {key: "FT4"}) SET b += {name: "Free T4", long_name: "Free thyroxine", panel: "thyroid", canonical_unit: "pmol/L"};
MERGE (l:LOINC {code: "3024-7"}) SET l.name = "Thyroxine (T4) free [Mass/volume] in Serum or Plasma";
MATCH (b:Biomarker {key: "FT4"}) MATCH (l:LOINC {code: "3024-7"}) MERGE (b)-[r:CODED_AS]->(l) SET r += {source: "loinc", evidence_level: "guideline", verified: true};
MERGE (r:FunctionalRange {id: "ft4_reference"}) SET r += {biomarker: "FT4", kind: "reference", sex: null, low: 10.0, high: 23.0, unit: "pmol/L", label: "Free T4 laboratory reference interval", source: "catalog", evidence_level: "expert_consensus", verified: true};
MATCH (b:Biomarker {key: "FT4"}) MATCH (r:FunctionalRange {id: "ft4_reference"}) MERGE (b)-[:HAS_RANGE]->(r);
MERGE (b:Biomarker {key: "TPOAB"}) SET b += {name: "Anti-TPO", long_name: "Thyroid peroxidase antibodies", panel: "thyroid", canonical_unit: "IU/mL"};
MERGE (l:LOINC {code: "8099-4"}) SET l.name = "Thyroperoxidase Ab [Units/volume] in Serum or Plasma";
MATCH (b:Biomarker {key: "TPOAB"}) MATCH (l:LOINC {code: "8099-4"}) MERGE (b)-[r:CODED_AS]->(l) SET r += {source: "loinc", evidence_level: "guideline", verified: true};
MERGE (r:FunctionalRange {id: "tpoab_reference"}) SET r += {biomarker: "TPOAB", kind: "reference", sex: null, low: 0.0, high: 35.0, unit: "IU/mL", label: "Anti-TPO laboratory reference interval", source: "catalog", evidence_level: "expert_consensus", verified: true};
MATCH (b:Biomarker {key: "TPOAB"}) MATCH (r:FunctionalRange {id: "tpoab_reference"}) MERGE (b)-[:HAS_RANGE]->(r);
MERGE (b:Biomarker {key: "VITD"}) SET b += {name: "Vitamin D (25-OH)", long_name: "25-hydroxyvitamin D", panel: "micronutrient", canonical_unit: "nmol/L"};
MERGE (l:LOINC {code: "62292-8"}) SET l.name = "25-Hydroxyvitamin D2+25-Hydroxyvitamin D3 [Mass/volume] in Serum or Plasma";
MATCH (b:Biomarker {key: "VITD"}) MATCH (l:LOINC {code: "62292-8"}) MERGE (b)-[r:CODED_AS]->(l) SET r += {source: "loinc", evidence_level: "guideline", verified: true};
MERGE (r:FunctionalRange {id: "vitd_reference"}) SET r += {biomarker: "VITD", kind: "reference", sex: null, low: 50.0, high: 125.0, unit: "nmol/L", label: "Vitamin D (25-OH) laboratory reference interval", source: "catalog", evidence_level: "expert_consensus", verified: true};
MATCH (b:Biomarker {key: "VITD"}) MATCH (r:FunctionalRange {id: "vitd_reference"}) MERGE (b)-[:HAS_RANGE]->(r);
MERGE (b:Biomarker {key: "B12"}) SET b += {name: "Vitamin B12", long_name: "Cobalamin (vitamin B12)", panel: "micronutrient", canonical_unit: "pmol/L"};
MERGE (l:LOINC {code: "2132-9"}) SET l.name = "Cobalamin (Vitamin B12) [Mass/volume] in Serum or Plasma";
MATCH (b:Biomarker {key: "B12"}) MATCH (l:LOINC {code: "2132-9"}) MERGE (b)-[r:CODED_AS]->(l) SET r += {source: "loinc", evidence_level: "guideline", verified: true};
MERGE (r:FunctionalRange {id: "b12_reference"}) SET r += {biomarker: "B12", kind: "reference", sex: null, low: 148.0, high: 664.0, unit: "pmol/L", label: "Vitamin B12 laboratory reference interval", source: "catalog", evidence_level: "expert_consensus", verified: true};
MATCH (b:Biomarker {key: "B12"}) MATCH (r:FunctionalRange {id: "b12_reference"}) MERGE (b)-[:HAS_RANGE]->(r);
MERGE (b:Biomarker {key: "FERRITIN"}) SET b += {name: "Ferritin", long_name: "Serum ferritin", panel: "micronutrient", canonical_unit: "ug/L"};
MERGE (l:LOINC {code: "2276-4"}) SET l.name = "Ferritin [Mass/volume] in Serum or Plasma";
MATCH (b:Biomarker {key: "FERRITIN"}) MATCH (l:LOINC {code: "2276-4"}) MERGE (b)-[r:CODED_AS]->(l) SET r += {source: "loinc", evidence_level: "guideline", verified: true};
MERGE (r:FunctionalRange {id: "ferritin_reference"}) SET r += {biomarker: "FERRITIN", kind: "reference", sex: null, low: 15.0, high: 300.0, unit: "ug/L", label: "Ferritin laboratory reference interval", source: "catalog", evidence_level: "expert_consensus", verified: true};
MATCH (b:Biomarker {key: "FERRITIN"}) MATCH (r:FunctionalRange {id: "ferritin_reference"}) MERGE (b)-[:HAS_RANGE]->(r);
MERGE (r:FunctionalRange {id: "ferritin_reference_f"}) SET r += {biomarker: "FERRITIN", kind: "reference", sex: "F", low: 15.0, high: 150.0, unit: "ug/L", label: "Ferritin laboratory reference interval (F)", source: "catalog", evidence_level: "expert_consensus", verified: true};
MATCH (b:Biomarker {key: "FERRITIN"}) MATCH (r:FunctionalRange {id: "ferritin_reference_f"}) MERGE (b)-[:HAS_RANGE]->(r);
MERGE (r:FunctionalRange {id: "ferritin_reference_m"}) SET r += {biomarker: "FERRITIN", kind: "reference", sex: "M", low: 30.0, high: 400.0, unit: "ug/L", label: "Ferritin laboratory reference interval (M)", source: "catalog", evidence_level: "expert_consensus", verified: true};
MATCH (b:Biomarker {key: "FERRITIN"}) MATCH (r:FunctionalRange {id: "ferritin_reference_m"}) MERGE (b)-[:HAS_RANGE]->(r);
MERGE (b:Biomarker {key: "MG"}) SET b += {name: "Magnesium", long_name: "Serum magnesium", panel: "micronutrient", canonical_unit: "mmol/L"};
MERGE (l:LOINC {code: "19123-9"}) SET l.name = "Magnesium [Mass/volume] in Serum or Plasma";
MATCH (b:Biomarker {key: "MG"}) MATCH (l:LOINC {code: "19123-9"}) MERGE (b)-[r:CODED_AS]->(l) SET r += {source: "loinc", evidence_level: "guideline", verified: true};
MERGE (r:FunctionalRange {id: "mg_reference"}) SET r += {biomarker: "MG", kind: "reference", sex: null, low: 0.7, high: 1.0, unit: "mmol/L", label: "Magnesium laboratory reference interval", source: "catalog", evidence_level: "expert_consensus", verified: true};
MATCH (b:Biomarker {key: "MG"}) MATCH (r:FunctionalRange {id: "mg_reference"}) MERGE (b)-[:HAS_RANGE]->(r);
MERGE (b:Biomarker {key: "ZINC"}) SET b += {name: "Zinc", long_name: "Serum zinc", panel: "micronutrient", canonical_unit: "umol/L"};
MERGE (l:LOINC {code: "5763-8"}) SET l.name = "Zinc [Mass/volume] in Serum or Plasma";
MATCH (b:Biomarker {key: "ZINC"}) MATCH (l:LOINC {code: "5763-8"}) MERGE (b)-[r:CODED_AS]->(l) SET r += {source: "loinc", evidence_level: "guideline", verified: true};
MERGE (r:FunctionalRange {id: "zinc_reference"}) SET r += {biomarker: "ZINC", kind: "reference", sex: null, low: 9.2, high: 18.4, unit: "umol/L", label: "Zinc laboratory reference interval", source: "catalog", evidence_level: "expert_consensus", verified: true};
MATCH (b:Biomarker {key: "ZINC"}) MATCH (r:FunctionalRange {id: "zinc_reference"}) MERGE (b)-[:HAS_RANGE]->(r);

// Conditions and symptoms
MERGE (c:Condition {id: "iron_deficiency"}) SET c.name = "Low iron stores (iron deficiency)";
MERGE (c:Condition {id: "subclinical_hypothyroidism"}) SET c.name = "Subclinical hypothyroidism pattern";
MERGE (c:Condition {id: "hypothyroidism"}) SET c.name = "Underactive thyroid pattern";
MERGE (c:Condition {id: "hyperthyroidism"}) SET c.name = "Overactive thyroid pattern";
MERGE (c:Condition {id: "autoimmune_thyroiditis"}) SET c.name = "Thyroid autoimmunity (e.g. Hashimoto's thyroiditis)";
MERGE (c:Condition {id: "vitamin_d_deficiency"}) SET c.name = "Low vitamin D status";
MERGE (c:Condition {id: "b12_deficiency"}) SET c.name = "Low vitamin B12 status";
MERGE (c:Condition {id: "hypomagnesemia"}) SET c.name = "Low magnesium";
MERGE (c:Condition {id: "zinc_deficiency"}) SET c.name = "Low zinc status";
MERGE (s:Symptom {id: "fatigue"}) SET s.name = "Chronic fatigue";
MERGE (s:Symptom {id: "brain_fog"}) SET s.name = "Brain fog";
MERGE (s:Symptom {id: "hair_loss"}) SET s.name = "Hair loss";

// Literature thresholds
MERGE (r:FunctionalRange {id: "ferritin_lt_15"}) SET r += {biomarker: "FERRITIN", kind: "threshold", op: "<", value: 15.0, unit: "ug/L", label: "Ferritin below 15 ug/L"};
MATCH (b:Biomarker {key: "FERRITIN"}) MATCH (r:FunctionalRange {id: "ferritin_lt_15"}) MERGE (b)-[:HAS_RANGE]->(r);
MERGE (r:FunctionalRange {id: "ferritin_lt_30"}) SET r += {biomarker: "FERRITIN", kind: "threshold", op: "<", value: 30.0, unit: "ug/L", label: "Ferritin below 30 ug/L"};
MATCH (b:Biomarker {key: "FERRITIN"}) MATCH (r:FunctionalRange {id: "ferritin_lt_30"}) MERGE (b)-[:HAS_RANGE]->(r);
MERGE (r:FunctionalRange {id: "tsh_gt_4"}) SET r += {biomarker: "TSH", kind: "threshold", op: ">", value: 4.0, unit: "mIU/L", label: "TSH above the reference interval"};
MATCH (b:Biomarker {key: "TSH"}) MATCH (r:FunctionalRange {id: "tsh_gt_4"}) MERGE (b)-[:HAS_RANGE]->(r);
MERGE (r:FunctionalRange {id: "tsh_gt_10"}) SET r += {biomarker: "TSH", kind: "threshold", op: ">", value: 10.0, unit: "mIU/L", label: "TSH above 10 mIU/L"};
MATCH (b:Biomarker {key: "TSH"}) MATCH (r:FunctionalRange {id: "tsh_gt_10"}) MERGE (b)-[:HAS_RANGE]->(r);
MERGE (r:FunctionalRange {id: "tsh_lt_0_4"}) SET r += {biomarker: "TSH", kind: "threshold", op: "<", value: 0.4, unit: "mIU/L", label: "TSH below the reference interval"};
MATCH (b:Biomarker {key: "TSH"}) MATCH (r:FunctionalRange {id: "tsh_lt_0_4"}) MERGE (b)-[:HAS_RANGE]->(r);
MERGE (r:FunctionalRange {id: "ft4_lt_10"}) SET r += {biomarker: "FT4", kind: "threshold", op: "<", value: 10.0, unit: "pmol/L", label: "Free T4 below the reference interval"};
MATCH (b:Biomarker {key: "FT4"}) MATCH (r:FunctionalRange {id: "ft4_lt_10"}) MERGE (b)-[:HAS_RANGE]->(r);
MERGE (r:FunctionalRange {id: "ft4_gt_23"}) SET r += {biomarker: "FT4", kind: "threshold", op: ">", value: 23.0, unit: "pmol/L", label: "Free T4 above the reference interval"};
MATCH (b:Biomarker {key: "FT4"}) MATCH (r:FunctionalRange {id: "ft4_gt_23"}) MERGE (b)-[:HAS_RANGE]->(r);
MERGE (r:FunctionalRange {id: "ft3_lt_3_1"}) SET r += {biomarker: "FT3", kind: "threshold", op: "<", value: 3.1, unit: "pmol/L", label: "Free T3 below the reference interval"};
MATCH (b:Biomarker {key: "FT3"}) MATCH (r:FunctionalRange {id: "ft3_lt_3_1"}) MERGE (b)-[:HAS_RANGE]->(r);
MERGE (r:FunctionalRange {id: "tpo_gt_35"}) SET r += {biomarker: "TPOAB", kind: "threshold", op: ">", value: 35.0, unit: "IU/mL", label: "Anti-TPO above assay cut-off"};
MATCH (b:Biomarker {key: "TPOAB"}) MATCH (r:FunctionalRange {id: "tpo_gt_35"}) MERGE (b)-[:HAS_RANGE]->(r);
MERGE (r:FunctionalRange {id: "vitd_lt_30"}) SET r += {biomarker: "VITD", kind: "threshold", op: "<", value: 30.0, unit: "nmol/L", label: "25-OH vitamin D below 30 nmol/L"};
MATCH (b:Biomarker {key: "VITD"}) MATCH (r:FunctionalRange {id: "vitd_lt_30"}) MERGE (b)-[:HAS_RANGE]->(r);
MERGE (r:FunctionalRange {id: "vitd_lt_50"}) SET r += {biomarker: "VITD", kind: "threshold", op: "<", value: 50.0, unit: "nmol/L", label: "25-OH vitamin D below 50 nmol/L"};
MATCH (b:Biomarker {key: "VITD"}) MATCH (r:FunctionalRange {id: "vitd_lt_50"}) MERGE (b)-[:HAS_RANGE]->(r);
MERGE (r:FunctionalRange {id: "b12_lt_148"}) SET r += {biomarker: "B12", kind: "threshold", op: "<", value: 148.0, unit: "pmol/L", label: "Vitamin B12 below 148 pmol/L"};
MATCH (b:Biomarker {key: "B12"}) MATCH (r:FunctionalRange {id: "b12_lt_148"}) MERGE (b)-[:HAS_RANGE]->(r);
MERGE (r:FunctionalRange {id: "mg_lt_0_7"}) SET r += {biomarker: "MG", kind: "threshold", op: "<", value: 0.7, unit: "mmol/L", label: "Magnesium below 0.70 mmol/L"};
MATCH (b:Biomarker {key: "MG"}) MATCH (r:FunctionalRange {id: "mg_lt_0_7"}) MERGE (b)-[:HAS_RANGE]->(r);
MERGE (r:FunctionalRange {id: "zinc_lt_9_2"}) SET r += {biomarker: "ZINC", kind: "threshold", op: "<", value: 9.2, unit: "umol/L", label: "Zinc below 9.2 umol/L"};
MATCH (b:Biomarker {key: "ZINC"}) MATCH (r:FunctionalRange {id: "zinc_lt_9_2"}) MERGE (b)-[:HAS_RANGE]->(r);

// Threshold -> condition evidence
MATCH (r:FunctionalRange {id: "ferritin_lt_15"}) MATCH (c:Condition {id: "iron_deficiency"}) MERGE (r)-[x:INDICATES]->(c) SET x += {source: "who_ferritin_2020", evidence_level: "guideline", verified: true, note: "WHO: ferritin <15 ug/L indicates iron deficiency in apparently healthy adults."};
MATCH (r:FunctionalRange {id: "ferritin_lt_30"}) MATCH (c:Condition {id: "iron_deficiency"}) MERGE (r)-[x:INDICATES]->(c) SET x += {source: "who_ferritin_2020", evidence_level: "expert_consensus", verified: true, note: "Higher cut-offs are used when inflammation may be present."};
MATCH (r:FunctionalRange {id: "ferritin_lt_30"}) MATCH (c:Condition {id: "subclinical_hypothyroidism"}) MERGE (r)-[x:AMPLIFIES]->(c) SET x += {source: "curated_hypothesis", evidence_level: "unverified", verified: false, note: "Low iron stores may compound fatigue attributed to borderline thyroid function."};
MATCH (r:FunctionalRange {id: "tsh_gt_4"}) MATCH (c:Condition {id: "subclinical_hypothyroidism"}) MERGE (r)-[x:INDICATES]->(c) SET x += {source: "ata_aace_2012", evidence_level: "guideline", verified: true, note: "Raised TSH with free T4 in range is the laboratory definition of subclinical hypothyroidism.", requires_biomarker: "FT4", requires_within_reference: true, requires_above: null};
MATCH (r:FunctionalRange {id: "tsh_gt_10"}) MATCH (c:Condition {id: "hypothyroidism"}) MERGE (r)-[x:INDICATES]->(c) SET x += {source: "ata_aace_2012", evidence_level: "guideline", verified: true, note: "TSH above 10 mIU/L is generally considered clinically significant."};
MATCH (r:FunctionalRange {id: "ft4_lt_10"}) MATCH (c:Condition {id: "hypothyroidism"}) MERGE (r)-[x:INDICATES]->(c) SET x += {source: "ata_aace_2012", evidence_level: "guideline", verified: true, note: "Low free T4 with raised TSH indicates overt hypothyroidism.", requires_biomarker: "TSH", requires_within_reference: false, requires_above: 4.0};
MATCH (r:FunctionalRange {id: "tsh_lt_0_4"}) MATCH (c:Condition {id: "hyperthyroidism"}) MERGE (r)-[x:INDICATES]->(c) SET x += {source: "ata_patient", evidence_level: "authoritative_review", verified: true, note: "A low TSH can reflect an overactive thyroid and needs clinical context."};
MATCH (r:FunctionalRange {id: "ft4_gt_23"}) MATCH (c:Condition {id: "hyperthyroidism"}) MERGE (r)-[x:INDICATES]->(c) SET x += {source: "ata_patient", evidence_level: "authoritative_review", verified: true, note: "Raised free T4 is consistent with an overactive thyroid."};
MATCH (r:FunctionalRange {id: "tpo_gt_35"}) MATCH (c:Condition {id: "autoimmune_thyroiditis"}) MERGE (r)-[x:INDICATES]->(c) SET x += {source: "ata_aace_2012", evidence_level: "guideline", verified: true, note: "TPO antibodies mark autoimmune thyroid disease and predict progression of subclinical hypothyroidism."};
MATCH (r:FunctionalRange {id: "tpo_gt_35"}) MATCH (c:Condition {id: "subclinical_hypothyroidism"}) MERGE (r)-[x:AMPLIFIES]->(c) SET x += {source: "ata_aace_2012", evidence_level: "guideline", verified: true, note: "Positive antibodies raise the likelihood that a raised TSH progresses."};
MATCH (r:FunctionalRange {id: "vitd_lt_30"}) MATCH (c:Condition {id: "vitamin_d_deficiency"}) MERGE (r)-[x:INDICATES]->(c) SET x += {source: "nih_ods_vitd", evidence_level: "authoritative_review", verified: true, note: "NIH ODS: levels below 30 nmol/L are associated with deficiency."};
MATCH (r:FunctionalRange {id: "vitd_lt_50"}) MATCH (c:Condition {id: "vitamin_d_deficiency"}) MERGE (r)-[x:INDICATES]->(c) SET x += {source: "nih_ods_vitd", evidence_level: "authoritative_review", verified: true, note: "NIH ODS: 30-50 nmol/L is generally considered inadequate for bone and overall health."};
MATCH (r:FunctionalRange {id: "b12_lt_148"}) MATCH (c:Condition {id: "b12_deficiency"}) MERGE (r)-[x:INDICATES]->(c) SET x += {source: "nih_ods_b12", evidence_level: "authoritative_review", verified: true, note: "Serum B12 below ~148 pmol/L (200 pg/mL) is commonly used to indicate deficiency."};
MATCH (r:FunctionalRange {id: "mg_lt_0_7"}) MATCH (c:Condition {id: "hypomagnesemia"}) MERGE (r)-[x:INDICATES]->(c) SET x += {source: "nih_ods_mg", evidence_level: "authoritative_review", verified: true, note: "Serum magnesium below the reference interval; serum levels poorly reflect total body stores."};
MATCH (r:FunctionalRange {id: "zinc_lt_9_2"}) MATCH (c:Condition {id: "zinc_deficiency"}) MERGE (r)-[x:INDICATES]->(c) SET x += {source: "nih_ods_zinc", evidence_level: "unverified", verified: false, note: "Serum zinc is an imperfect marker of zinc status."};
MATCH (r:FunctionalRange {id: "ft3_lt_3_1"}) MATCH (c:Condition {id: "hypothyroidism"}) MERGE (r)-[x:AMPLIFIES]->(c) SET x += {source: "curated_hypothesis", evidence_level: "unverified", verified: false, note: "Low free T3 in isolation is non-specific (e.g. illness, low intake)."};

// Condition -> symptom evidence
MATCH (c:Condition {id: "iron_deficiency"}) MATCH (s:Symptom {id: "fatigue"}) MERGE (c)-[x:PRESENTS_WITH]->(s) SET x += {source: "who_ferritin_2020", evidence_level: "authoritative_review", verified: true, note: ""};
MATCH (c:Condition {id: "iron_deficiency"}) MATCH (s:Symptom {id: "hair_loss"}) MERGE (c)-[x:PRESENTS_WITH]->(s) SET x += {source: "curated_hypothesis", evidence_level: "unverified", verified: false, note: ""};
MATCH (c:Condition {id: "iron_deficiency"}) MATCH (s:Symptom {id: "brain_fog"}) MERGE (c)-[x:PRESENTS_WITH]->(s) SET x += {source: "curated_hypothesis", evidence_level: "unverified", verified: false, note: ""};
MATCH (c:Condition {id: "hypothyroidism"}) MATCH (s:Symptom {id: "fatigue"}) MERGE (c)-[x:PRESENTS_WITH]->(s) SET x += {source: "ata_patient", evidence_level: "authoritative_review", verified: true, note: ""};
MATCH (c:Condition {id: "hypothyroidism"}) MATCH (s:Symptom {id: "brain_fog"}) MERGE (c)-[x:PRESENTS_WITH]->(s) SET x += {source: "ata_patient", evidence_level: "authoritative_review", verified: true, note: ""};
MATCH (c:Condition {id: "hypothyroidism"}) MATCH (s:Symptom {id: "hair_loss"}) MERGE (c)-[x:PRESENTS_WITH]->(s) SET x += {source: "ata_patient", evidence_level: "authoritative_review", verified: true, note: ""};
MATCH (c:Condition {id: "subclinical_hypothyroidism"}) MATCH (s:Symptom {id: "fatigue"}) MERGE (c)-[x:PRESENTS_WITH]->(s) SET x += {source: "ata_aace_2012", evidence_level: "observational", verified: true, note: ""};
MATCH (c:Condition {id: "subclinical_hypothyroidism"}) MATCH (s:Symptom {id: "brain_fog"}) MERGE (c)-[x:PRESENTS_WITH]->(s) SET x += {source: "curated_hypothesis", evidence_level: "unverified", verified: false, note: ""};
MATCH (c:Condition {id: "hyperthyroidism"}) MATCH (s:Symptom {id: "fatigue"}) MERGE (c)-[x:PRESENTS_WITH]->(s) SET x += {source: "ata_patient", evidence_level: "authoritative_review", verified: true, note: ""};
MATCH (c:Condition {id: "hyperthyroidism"}) MATCH (s:Symptom {id: "hair_loss"}) MERGE (c)-[x:PRESENTS_WITH]->(s) SET x += {source: "ata_patient", evidence_level: "authoritative_review", verified: true, note: ""};
MATCH (c:Condition {id: "autoimmune_thyroiditis"}) MATCH (s:Symptom {id: "fatigue"}) MERGE (c)-[x:PRESENTS_WITH]->(s) SET x += {source: "curated_hypothesis", evidence_level: "unverified", verified: false, note: ""};
MATCH (c:Condition {id: "vitamin_d_deficiency"}) MATCH (s:Symptom {id: "fatigue"}) MERGE (c)-[x:PRESENTS_WITH]->(s) SET x += {source: "curated_hypothesis", evidence_level: "unverified", verified: false, note: ""};
MATCH (c:Condition {id: "b12_deficiency"}) MATCH (s:Symptom {id: "fatigue"}) MERGE (c)-[x:PRESENTS_WITH]->(s) SET x += {source: "nih_ods_b12", evidence_level: "authoritative_review", verified: true, note: ""};
MATCH (c:Condition {id: "b12_deficiency"}) MATCH (s:Symptom {id: "brain_fog"}) MERGE (c)-[x:PRESENTS_WITH]->(s) SET x += {source: "nih_ods_b12", evidence_level: "authoritative_review", verified: true, note: ""};
MATCH (c:Condition {id: "hypomagnesemia"}) MATCH (s:Symptom {id: "fatigue"}) MERGE (c)-[x:PRESENTS_WITH]->(s) SET x += {source: "nih_ods_mg", evidence_level: "authoritative_review", verified: true, note: ""};
MATCH (c:Condition {id: "zinc_deficiency"}) MATCH (s:Symptom {id: "hair_loss"}) MERGE (c)-[x:PRESENTS_WITH]->(s) SET x += {source: "nih_ods_zinc", evidence_level: "authoritative_review", verified: true, note: ""};

// Curated biomarker correlations
MATCH (a:Biomarker {key: "TSH"}) MATCH (b:Biomarker {key: "FT4"}) MERGE (a)-[x:CORRELATES_WITH]->(b) SET x += {source: "ata_aace_2012", evidence_level: "guideline", verified: true, note: "", direction: "inverse"};
MATCH (a:Biomarker {key: "TPOAB"}) MATCH (b:Biomarker {key: "TSH"}) MERGE (a)-[x:CORRELATES_WITH]->(b) SET x += {source: "ata_aace_2012", evidence_level: "observational", verified: true, note: "", direction: "positive"};
